### ISSUE TITLE
老哥我看到很多都是域名加端口的网站比如（xxx.baidu.com:6778）这种怎么具体收集啊

### ISSUE THREAD

**Issue by gusechuisheng** [Paper-Pen/GatherInfo#2]

**Comment by Paper-Pen** [comment]
用这个工具webalivescan



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月31日(周一) 上午10:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Paper-Pen/GatherInfo] 老哥我看到很多都是域名加端口的网站比如（xxx.baidu.com:6778）这种怎么具体收集啊 (#2)




 
Closed #2.

**Comment by Paper-Pen** [comment]
webalivescan不更新了，可以用bscan，同一个作者的
