### ISSUE TITLE
google hacking语法

### ISSUE THREAD

**Issue by LztCode** [Paper-Pen/GatherInfo#3]
把/换成空格|空格能一起搜
site:xxx.com 管理后台 | 登陆 | 管理员 | 系统

**Comment by Paper-Pen** [comment]
给力，已采纳👍

**Comment by Paper-Pen** [comment]
> 把/换成空格|空格能一起搜
> site:xxx.com 管理后台 | 登陆 | 管理员 | 系统

给力，已采纳👍

**Comment by Paper-Pen** [comment]
> 把/换成空格|空格能一起搜
> site:xxx.com 管理后台 | 登陆 | 管理员 | 系统

不可以，这样查询的结果不全是site指定的网站。

**Comment by LztCode** [comment]
> > 把/换成空格|空格能一起搜
> > site:xxx.com 管理后台 | 登陆 | 管理员 | 系统
> 
> 不可以，这样查询的结果不全是site指定的网站。

这样啊, 好的

**Comment by Paper-Pen** [comment]
> > > 把/换成空格|空格能一起搜
> > > site:xxx.com 管理后台 | 登陆 | 管理员 | 系统
> > 
> > 
> > 不可以，这样查询的结果不全是site指定的网站。
> 
> 这样啊, 好的

已采纳感谢，用Google搜索是可以的，百度不行
